name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DatabaseMigrationSystem/DatabaseMigrationSystem.Web/

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    # Build
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -r linux-x64 -o cur
    # Deploy
    - run: rsync --rsh="sshpass -p ${{secrets.PASSWORD}} ssh -o StrictHostKeyChecking=no -l ${{secrets.USERNAME}}" --archive --compress --delete /home/runner/work/DatabaseMigrationSystem/DatabaseMigrationSystem.Web/cur/ ${{secrets.HOST}}:/srv/app/
    - name: restart service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: systemctl restart migrations
